### ISSUE TITLE
为什么我用了这个镜像还是从maven中央仓库下载jar包？

### ISSUE THREAD

**Issue by luyuanx2** [AliyunContainerService/maven-image#1]
![image](https://user-images.githubusercontent.com/26129033/40520969-9ea9b2e2-5ffb-11e8-8399-9b2427766b91.png)
![image](https://user-images.githubusercontent.com/26129033/40521009-e4076884-5ffb-11e8-830d-7aa26c589858.png)

**Comment by denverdino** [comment]
请参考 https://yq.aliyun.com/articles/65274

**Comment by luyuanx2** [comment]
谢谢，问题已解决
